---
- name: download ambari repo
  get_url:
    url: http://public-repo-1.hortonworks.com/ambari/centos6/2.x/updates/2.4.2.0/ambari.repo
    dest: /etc/yum.repos.d/ambari.repo

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: installing ambari-server
  yum:
    name: ambari-server
    state: latest

- name: setup ambari server
  shell: ambari-server setup -s && touch /etc/ambari-server/configured

- name: Add Metron service to Ambari by running mpack
  shell: ambari-server install-mpack --mpack=/root/metron/metron-deployment/packaging/ambari/metron-mpack/target/metron_mpack-0.4.0.0.tar.gz --verbose
  ignore_errors: yes

- name: start amabri
  shell: ambari-server start
  ignore_errors: yes
